---
version: 0.0.1
slug: matterflow
name: Matterflow
description: Matterflow - the data intelligence hub for Matter
url: https://github.com/MatterCoder/addon-matterflow
image: "oideibrett/image-{arch}-matterflow"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant_api: true
host_network: true
panel_admin: false
hassio_api: true
ingress: false
ingress_stream: false
webui: http://[HOST]:[PORT:4173]
init: false
map:
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
  - addon_config:rw
ports:
  4173/tcp: 4173
  5173/tcp: 5173
  8000/tcp: 8000
  9001/tcp: 9001
ports_description:
  9001/tcp: Supervisord Web interface
